<?php
$this->breadcrumbs=array(
	'Providers'=>array('index'),
	$model->name,
);

$this->menu=array(
array('label'=>'List Providers','url'=>array('index')),
array('label'=>'Create Providers','url'=>array('create')),
array('label'=>'Update Providers','url'=>array('update','id'=>$model->id)),
array('label'=>'Delete Providers','url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
array('label'=>'Manage Providers','url'=>array('admin')),
);
?>

<h1>View Providers #<?php echo $model->id; ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
'data'=>$model,
'attributes'=>array(
		'id',
		'type',
		'prefix',
		'name',
		'status',
		'currency',
		'country_id',
		'model',
		'net_payment',
		'deal',
		'post_payment_amount',
		'start_date',
		'end_date',
		'daily_cap',
		'sizes',
		'has_s2s',
		'callback',
		'placeholder',
		'has_token',
		'commercial_name',
		'state',
		'zip_code',
		'address',
		'contact_com',
		'email_com',
		'contact_adm',
		'email_adm',
		'entity',
		'tax_id',
		'prospect',
		'pdf_name',
		'pdf_agreement',
		'phone',
		'foundation_date',
		'foundation_place',
		'bank_account_name',
		'bank_account_number',
		'branch',
		'bank_name',
		'swift_code',
		'percent_off',
		'url',
		'use_alternative_convention_name',
		'has_api',
		'use_vectors',
		'query_string',
		'token1',
		'token2',
		'token3',
		'publisher_percentage',
		'rate',
		'users_id',
		'account_manager_id',
),
)); ?>
