<h5>Providers</h5>
<?php $this->widget('bootstrap.widgets.TbDetailView', array(
    'type'=>'striped bordered condensed',
	'data'=>$model,
	'attributes'=>array(
		'id',
		'prefix',
		'name',
		'currency',
		'entity',
		'status',
		array(
			'label' =>$model->getAttributeLabel('country_id'),
			'name' =>'country.name',
		),
		'model',
		'net_payment',
		'deal',
		'post_payment_amount',
		'start_date',
		'end_date',
		'daily_cap',
		'sizes',
		'commercial_name',
		'state',
		'zip_code',
		'address',
		'contact_com',
		'email_com',
		'contact_adm',
		'email_adm',
		'entity',
		'tax_id',
		array(
			'label' =>$model->getAttributeLabel('has_s2s'),
			'value' =>$model->has_s2s ? "Yes" : "No",
		),
		'callback',
		array(
			'label' =>$model->getAttributeLabel('has_token'),
			'value' =>$model->has_token ? "Yes" : "No",
		),
		'placeholder',
	),
)); ?>